[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "binance-fetcher"
version = "0.1.0"
dependencies = [
    "appdirs",
    "pandas",
    "requests",
    "pathlib",
    "rich"
]